const Images = {
  walter: require("./images/walter.jpeg"),
  linkedin: require("./images/linkedin.png"),
  github: require("./images/github.png"),
  phone: {
    src: require("./images/phone/iphone_hardware_portrait_large.png"),
    srcSet: `${require("./images/phone/iphone_hardware_portrait_large_2x.png")} 2x`,
  },
  techStackBefore: {
    games: {
      actionscript3: require("./images/techStackBefore/actionscript3.png"),
      flash: require("./images/techStackBefore/flash.png"),
      unity3d: require("./images/techStackBefore/unity3d.png"),
      html5Canvas: require("./images/techStackBefore/html5_canvas.png"),
      java: require("./images/techStackBefore/java.png"),
      msdotnet: require("./images/techStackBefore/msdotnet.png"),
      csharp: require("./images/techStackBefore/csharp.png"),
      mssql: require("./images/techStackBefore/mssql.png"),
    },
    applications: {
      css: require("./images/techStackUsing/css.png"),
      cypress: require("./images/techStackUsing/cypress.png"),
      electron: require("./images/techStackUsing/electron.png"),
      firebase: require("./images/techStackUsing/firebase.png"),
      flutter: require("./images/techStackUsing/flutter.png"),
      graphql: require("./images/techStackUsing/graphql.png"),
      html: require("./images/techStackUsing/html.png"),
      javascript: require("./images/techStackUsing/javascript.png"),
      jest: require("./images/techStackUsing/jest.png"),
      react: require("./images/techStackUsing/react.png"),
      redux: require("./images/techStackUsing/redux.png"),
      swiftui: require("./images/techStackUsing/swiftui.png"),
      typescript: require("./images/techStackUsing/typescript.png"),
      sketch: require("./images/techStackUsing/sketch.png"),
      adobexd: require("./images/techStackUsing/adobexd.png"),
      zeplin: require("./images/techStackUsing/zeplin.png"),
      node: require("./images/techStackUsing/nodejs.png"),
      webstorm: require("./images/techStackUsing/webstorm.png"),
      vscode: require("./images/techStackUsing/vscode.png"),
      xcode: require("./images/techStackUsing/xcode.png"),
      androidStudio: require("./images/techStackUsing/android_studio.png"),
      mongodb: require("./images/techStackUsing/mongodb.png"),
      photoshop: require("./images/techStackUsing/photoshop.png"),
    },
  },
  sideProjects: {
    walterscc: require("./images/sideProjects/walterscc.png"),
    waltersccScreenshot: require("./images/sideProjects/walterscc-screenshot.png"),
    mgl: require("./images/sideProjects/mgl.png"),
    mglScreenshot: require("./images/sideProjects/mgl-screenshot.png"),
    whatTheFOOD: require("./images/sideProjects/what-the-food.png"),
    displayConnectedWifiName: require("./images/sideProjects/display-connected-wifi-name.png"),
    displayConnectedWifiNameScreenshot: require("./images/sideProjects/display-connected-wifi-name-screenshot.png"),
    scrollToTop: require("./images/sideProjects/scroll-to-top.png"),
    scrollToTopScreenshot: require("./images/sideProjects/scroll-to-top-screenshot.png"),
    storeDownloadBadges: {
      appstore: require("./images/sideProjects/store-download-badges/appstore.svg"),
      playstore: require("./images/sideProjects/store-download-badges/playstore.png"),
      macAppStore: require("./images/sideProjects/store-download-badges/mac-app-store.svg"),
    },
  },
  replay: require("./images/replay.svg"),
};

export { Images };
